import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { expect, test } from "vitest";

// Exact projects generated by the published create-lace@0.1.0-alpha.1 tarball;
// the upgrade acceptance starts from these bytes.
for (const variant of ["default", "cloudflare"]) {
  test(`${variant} template 0.4.0 fixture matches its own ownership manifest`, async () => {
    const fixture = JSON.parse(
      await readFile(new URL(`fixtures/template-0.4.0/${variant}.json`, import.meta.url), "utf8"),
    );
    expect(fixture.generator).toEqual({
      package: "create-lace@0.1.0-alpha.1",
      npmShasum: "cd8e6c262a2078873662dc30a2783eb4f3bc3f62",
      sha256: "b91bd4a1920453ccc2c69fdd07cbb50438fee2c5b4c55274d09c584a80d2cd97",
      templateVersion: "0.4.0",
    });
    const manifest = JSON.parse(fixture.files[".lace/manifest.json"]);
    expect(manifest.templateVersion).toBe("0.4.0");
    expect(Object.keys(manifest.files).sort()).toEqual(
      Object.keys(fixture.files)
        .filter((path) => path !== ".lace/manifest.json")
        .sort(),
    );
    for (const [path, record] of Object.entries(manifest.files)) {
      if (record.owner !== "managed") continue;
      const digest = createHash("sha256").update(fixture.files[path], "utf8").digest("hex");
      expect(digest, path).toBe(record.sha256);
    }
    expect("wrangler.jsonc" in fixture.files).toBe(variant === "cloudflare");
    expect("README.md" in fixture.files).toBe(false);
  });
}
