// Generated by Lace. `lace add block` maintains this file; edits are reported as conflicts.
import { builtInBlocks } from "@lacecms/content";
import { defineBlockMap } from "@lacecms/render";
import CtaBlock from "../components/lace/CtaBlock.astro";
import HeroBlock from "../components/lace/HeroBlock.astro";
import ImageBlock from "../components/lace/ImageBlock.astro";
import QuoteBlock from "../components/lace/QuoteBlock.astro";
import RichTextBlock from "../components/lace/RichTextBlock.astro";

export const blocks = defineBlockMap({
  cta: { definition: builtInBlocks.cta, component: CtaBlock },
  hero: { definition: builtInBlocks.hero, component: HeroBlock },
  image: { definition: builtInBlocks.image, component: ImageBlock },
  quote: { definition: builtInBlocks.quote, component: QuoteBlock },
  richText: { definition: builtInBlocks.richText, component: RichTextBlock },
});
