import { importSpecifier } from "./blocks-site.js";

export const MAP_HEADER =
  "// Generated by Lace. `lace add block` maintains this file; edits are reported as conflicts.";

export interface MapEntry {
  readonly type: string;
  /** Site-relative component path. */
  readonly component: string;
  /** Export name in the definitions module; undefined for built-in definitions. */
  readonly definitionExport?: string;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/u;
const property = (key: string): string => (IDENTIFIER.test(key) ? key : JSON.stringify(key));
const member = (object: string, key: string): string =>
  IDENTIFIER.test(key) ? `${object}.${key}` : `${object}[${JSON.stringify(key)}]`;

export function componentName(path: string): string {
  return (path.split("/").at(-1) ?? path).replace(/\.[^.]+$/u, "");
}

/** `pricing-table` -> `PricingTableBlock.astro`. */
export function customComponentFile(type: string): string {
  const pascal = type
    .split("-")
    .filter((part) => part.length > 0)
    .map((part) => `${part[0]!.toUpperCase()}${part.slice(1)}`)
    .join("");
  return `${pascal}Block.astro`;
}

/** Module specifier for the definitions module; a `.ts` extension is left to the bundler. */
export function definitionsSpecifier(fromFile: string, definitions: string): string {
  return importSpecifier(fromFile, definitions).replace(/\.ts$/u, "");
}

function imports(entry: MapEntry, blockMap: string): string {
  return `import ${componentName(entry.component)} from "${importSpecifier(blockMap, entry.component)}";`;
}

function line(entry: MapEntry): string {
  const definition =
    entry.definitionExport === undefined
      ? member("builtInBlocks", entry.type)
      : member("definitions", entry.definitionExport);
  return `  ${property(entry.type)}: { definition: ${definition}, component: ${componentName(entry.component)} },`;
}

export function renderBlockMap(
  blockMap: string,
  entries: readonly MapEntry[],
  definitions: string | undefined,
): Buffer {
  const sorted = [...entries].sort((a, b) => a.type.localeCompare(b.type));
  const header = [MAP_HEADER];
  if (sorted.some((entry) => entry.definitionExport === undefined))
    header.push('import { builtInBlocks } from "@lacecms/content";');
  if (sorted.some((entry) => entry.definitionExport !== undefined) && definitions !== undefined)
    header.push(`import * as definitions from "${definitionsSpecifier(blockMap, definitions)}";`);
  header.push('import { defineBlockMap } from "@lacecms/render";');
  header.push(...sorted.map((entry) => imports(entry, blockMap)));
  const body =
    sorted.length === 0
      ? "export const blocks = defineBlockMap({});"
      : `export const blocks = defineBlockMap({\n${sorted.map(line).join("\n")}\n});`;
  return Buffer.from(`${header.join("\n")}\n\n${body}\n`);
}

/** Exact lines a user adds to an edited map for blocks it does not register yet. */
export function missingMapLines(
  current: string,
  blockMap: string,
  entries: readonly MapEntry[],
  definitions: string | undefined,
): string[] {
  const missing = [...entries]
    .sort((a, b) => a.type.localeCompare(b.type))
    .filter((entry) => !current.includes(line(entry).trim()));
  if (missing.length === 0) return [];
  const result: string[] = [];
  if (
    missing.some((entry) => entry.definitionExport === undefined) &&
    !current.includes("builtInBlocks")
  )
    result.push('import { builtInBlocks } from "@lacecms/content";');
  if (
    definitions !== undefined &&
    missing.some((entry) => entry.definitionExport !== undefined) &&
    !current.includes("* as definitions")
  )
    result.push(`import * as definitions from "${definitionsSpecifier(blockMap, definitions)}";`);
  for (const entry of missing) {
    const statement = imports(entry, blockMap);
    if (!current.includes(statement)) result.push(statement);
  }
  result.push(...missing.map((entry) => line(entry).trim()));
  return result;
}

export interface ScaffoldField {
  readonly type: string;
  readonly required?: boolean;
  readonly defaultValue?: unknown;
}

function fieldMarkup(key: string, field: ScaffoldField): string {
  const value = member("data", key);
  const part = JSON.stringify(key);
  let markup: string;
  switch (field.type) {
    case "richText":
      markup = `<div data-lace-part=${part}><RichText context={{ block: context, fieldPath: [${part}] }} document={${value}} /></div>`;
      break;
    case "media":
      markup = `<img alt="" data-lace-part=${part} src={mediaUrl(${value})} />`;
      break;
    case "url":
      markup = `<a data-lace-part=${part} href={${value}}>{${value}}</a>`;
      break;
    case "boolean":
      markup = `<p data-lace-part=${part} data-lace-state={${value} ? "on" : "off"}>{${value} ? "Yes" : "No"}</p>`;
      break;
    default:
      markup = `<p data-lace-part=${part}>{${value}}</p>`;
  }
  const required = field.required === true || field.defaultValue !== undefined;
  return required ? `  ${markup}` : `  {${value} !== undefined && ${markup}}`;
}

/** A starting component for a configured custom block; the user owns it afterwards. */
export function renderCustomScaffold(options: {
  readonly component: string;
  readonly definitions: string;
  readonly definitionExport: string;
  readonly fields: Readonly<Record<string, ScaffoldField>>;
}): Buffer {
  const fields = Object.entries(options.fields);
  const usesRichText = fields.some(([, field]) => field.type === "richText");
  const usesMedia = fields.some(([, field]) => field.type === "media");
  const props = [
    "block",
    ...(usesRichText ? ["context"] : []),
    "data",
    ...(usesMedia ? ["mediaUrl"] : []),
  ];
  const lines = [
    "---",
    ...(usesRichText ? ['import RichText from "@lacecms/astro/RichText.astro";'] : []),
    'import type { BlockProps } from "@lacecms/render";',
    `import type * as definitions from "${definitionsSpecifier(options.component, options.definitions)}";`,
    "",
    `type Props = BlockProps<typeof ${member("definitions", options.definitionExport)}>;`,
    "",
    `const { ${props.join(", ")} } = Astro.props;`,
    "---",
    "",
    "<section data-lace-block={block.type} data-lace-block-key={block.key}>",
    ...fields.map(([key, field]) => fieldMarkup(key, field)),
    "</section>",
  ];
  return Buffer.from(`${lines.join("\n")}\n`);
}
